notifications:
  email: false
  irc:
    template:
    - "%{build_url} : (%{branch} - %{commit} - %{commit_subject} : %{author}): %{message}"
    channels:
    - secure: ptwEa7VTrvabhO02GxlHPPfnA2JgLDuWvMiWfQXfJzAptHD6I1wxIqs4dFv8POVGcaAOmAt2QGJX1CVZvQmaYu02ecdyTwprwo598AzfBFtRkYKGnu9QqjwK3RYSGjN0AQXZQdG+VV/W1cBa7lpKc6B9UZAtxu96atVn+epGuYioDnwukrV3J72/57eQh/WYDMoHzKXhqHAfkWT9rhoIb7PDRRDg9ZXWJjm2UIC4OUTGWSCEXMQbiqrorvJOvdfQj6dbXsi8X7yFD9Qa458pvFSnTgIsFktVzAWybpttekGnxogR5CAJOcWyvAqNnbs38oZ95+GTd5yKk5OZfyaN9K9FEbEhEaYzvkHBNgvAXIPwCIc5sIH19zDLgna3AVp/EDJFSyjIBjdF91RzyjzR5Q/LfbEu9HSHi3Fv9GJEY6vj194F6GgNjwBULGIx9GibK+xj8tP0wZe/7y9tPxLDxni+ZjsyeyrPi1g8AOduO0tK/mKxDjHCW+41utZVfc7G1tXMIvxBiW0RGIb8z8VaoQfXKqju/RKil1IQXBdKE1Ofv1scDT5Pf9ypKT632c5l4TmKKL9SUIlhpFUBfagroXlapGDmpR2DV1twW4+4Z1UVfzdK859Hb+omblEs6NDv9JNvB8Xqrd0miNpoBHmRZqqrNX9x8Lmc+NCX4H0EDDM=
  slack:
    secure: drnu7xn2ubvypoWdau5BNX6tcSc5+4Db+iEekUd2FAyb0xwsbD1/Bu4at2IYblZSTwUPfsGeIxp6FBQa+iHPLB0YJ5aXyAvd30S3TB7eM/96pqGzGHwiZv8Wt/Y5VfWRCdcOA1FZWqRDCPP5k+GPbVK/v6cYJ8BssK9Vzf+XQ6JH2/MfYbgk0pUxsLe314/NvFluZzGYlfyycj9esgzaCmDUmn8BiekVhxayyogLdezVyr+l5Wpw+iKdD3KlxT8naNeU+UNlsGsDG9F20nFm9ukAHU2WQqG4wjT1vfxgbbMfZbZJf/RQflhlwX0bgSv3RHQr26jKC3K7TNM0tErB82yBllwbuKMOV0kkgrmOlr1Qb//ynKym2u4xFs0nFO8rdIn0WDj0/k+eqJWaJAjtEvXjYl/0+VmpTlZj78L/Ms80hGU/EY2MFnwVhv3vSn1g6qvSQY5kPq1/+SiA5aDw7vjn7fVm+AkAAmobx9k+fYK9n8M28DhGmRZ3FjTbNrnkUPw1ypSZsrpu6w6O38op3U+kjYiWYC/F0hgo85Ae9is8V5EsHKZlFrydrp44e7m67LTO/nLowGExR+BKwLNcSmdqSRiaTX6Bwvx2ht/a3CJP1JGQssYhaujDYq1eTwlo1zaN04H782ExUWrFIBOkp2lkbxONEzFd97lG1OTzanI=
env:
  matrix:
  - secure: Obqxk8oHTTTbr3Km0qbq07St5wFWD1yxBvuBO+mf0WtAmK3gMzUXnHV4ZxHLoWgFG5PG3gLO3EPbt0ToVO6CR0Kg+FbS7EissVfZ5cOMbObURdZCO3aV3AZ0ws/usphjj5Wl4MOsAKOa3dUPK3/oDyZ8ekcWILomiO/RustvEhQvpmexx4dwh5Y8JfvZihCRKEta2C0sxjafMyLS/nZB0tyGukRFvfe672tlUFn/KDfOBSElXTPLxEXvsEqf5YB7f5qHikXN9SpEwW6j5X1BrbIto3NPwz9+JbxLylW0vXJTwV4IADsS9bjGIK5G4T63IBYeMTXoeUfPmaah73ZrXLMkFXH+UKdEPRpgbD3QCD82iRtJmKq9Lk/L8nqDoyI03VkqAqddaIToCxtQR1q5/Pq0DdCN0zgUPDQjKW3W8K8gqWg8mfRBYmN6hxVKXrazdQqCPr+9VV3pSZ4zDtDFcGAgJ1zTy3H5hasquPsm88Fx9ErofGbn6keoMoezuBiKdw3PvYJGPbyaucIxbIQTh3qZzqhLkW8kL9bOs6TgTAq0m1mx2xv/At6USJaxOTyROID9y8c0y3acY7KecyttrMG4GzjgaphAyuRB8xHQXmElgXiR96LftHc7lNQfslaxcGzsmemE/jI62AZ14Ar4swi1qzfeJsc6J/0R8p27Hg0=
services:
- docker
before_script:
- docker login --email='.' --username="docku+docku" --password="${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
- wget -O /tmp/dumb-init.tar.gz 'https://github.com/Yelp/dumb-init/archive/v0.5.0.tar.gz'
- tar --strip-components=1 -xf /tmp/dumb-init.tar.gz
- make build
script:
- docker build -t quay.io/docku/dumb-init .
after_script:
- docker push quay.io/docku/dumb-init
