notifications:
  email: false
  irc:
    template:
    - "%{build_url} : (%{branch} - %{commit} - %{commit_subject} : %{author}): %{message}"
    channels:
    - secure: ptwEa7VTrvabhO02GxlHPPfnA2JgLDuWvMiWfQXfJzAptHD6I1wxIqs4dFv8POVGcaAOmAt2QGJX1CVZvQmaYu02ecdyTwprwo598AzfBFtRkYKGnu9QqjwK3RYSGjN0AQXZQdG+VV/W1cBa7lpKc6B9UZAtxu96atVn+epGuYioDnwukrV3J72/57eQh/WYDMoHzKXhqHAfkWT9rhoIb7PDRRDg9ZXWJjm2UIC4OUTGWSCEXMQbiqrorvJOvdfQj6dbXsi8X7yFD9Qa458pvFSnTgIsFktVzAWybpttekGnxogR5CAJOcWyvAqNnbs38oZ95+GTd5yKk5OZfyaN9K9FEbEhEaYzvkHBNgvAXIPwCIc5sIH19zDLgna3AVp/EDJFSyjIBjdF91RzyjzR5Q/LfbEu9HSHi3Fv9GJEY6vj194F6GgNjwBULGIx9GibK+xj8tP0wZe/7y9tPxLDxni+ZjsyeyrPi1g8AOduO0tK/mKxDjHCW+41utZVfc7G1tXMIvxBiW0RGIb8z8VaoQfXKqju/RKil1IQXBdKE1Ofv1scDT5Pf9ypKT632c5l4TmKKL9SUIlhpFUBfagroXlapGDmpR2DV1twW4+4Z1UVfzdK859Hb+omblEs6NDv9JNvB8Xqrd0miNpoBHmRZqqrNX9x8Lmc+NCX4H0EDDM=
  slack:
    secure: drnu7xn2ubvypoWdau5BNX6tcSc5+4Db+iEekUd2FAyb0xwsbD1/Bu4at2IYblZSTwUPfsGeIxp6FBQa+iHPLB0YJ5aXyAvd30S3TB7eM/96pqGzGHwiZv8Wt/Y5VfWRCdcOA1FZWqRDCPP5k+GPbVK/v6cYJ8BssK9Vzf+XQ6JH2/MfYbgk0pUxsLe314/NvFluZzGYlfyycj9esgzaCmDUmn8BiekVhxayyogLdezVyr+l5Wpw+iKdD3KlxT8naNeU+UNlsGsDG9F20nFm9ukAHU2WQqG4wjT1vfxgbbMfZbZJf/RQflhlwX0bgSv3RHQr26jKC3K7TNM0tErB82yBllwbuKMOV0kkgrmOlr1Qb//ynKym2u4xFs0nFO8rdIn0WDj0/k+eqJWaJAjtEvXjYl/0+VmpTlZj78L/Ms80hGU/EY2MFnwVhv3vSn1g6qvSQY5kPq1/+SiA5aDw7vjn7fVm+AkAAmobx9k+fYK9n8M28DhGmRZ3FjTbNrnkUPw1ypSZsrpu6w6O38op3U+kjYiWYC/F0hgo85Ae9is8V5EsHKZlFrydrp44e7m67LTO/nLowGExR+BKwLNcSmdqSRiaTX6Bwvx2ht/a3CJP1JGQssYhaujDYq1eTwlo1zaN04H782ExUWrFIBOkp2lkbxONEzFd97lG1OTzanI=
env:
  matrix:
  - secure: JMNipsf1inbM60seeA65AlkCgxj15EGFU+WlXuChUVtLaY0DgPE0Ckc0PGvQ6LGUyLGV2i8+9A4ubxGdYIt5Wzv8OOtxWqZvD7PPrSO1VS64dUFiqpQlKBRXKScQHFknUnQTFy5ug+cHnFgB0Hfx4CAsOzOY4Uhx2qv2SOCC5fo1sV4t2/PCSu/tIjpky3bRuGDZt7yQJ+b6sBNot0Zi+MXJQS3i2iZvsO3Mkiqspx6n5Zt9LsgRTCftURijeDvCTYsJPqCB89NBxiMz/0NX3305heNkarzaHqfCy60f7cOs7LWU547omYZr2LWXWzkx8+cZAiALnFT4VeXKAlHHjo+5uh9+z/V6ov3h/4WyyLSFnrUkq8MWDXIFAstpbIssqT6TnEYY8fQp+dPhOn/T6ZtFvqYINOSnh8r28oqrPbNyNnLHgcMmEiz4k+x1UzR0nHAsg5gGZ8kT0qz4KLCtSi4kv0njfllG78jxbatvgKXj8Gz9TE+ysxdaAnrI3HhdjnJ94KBodkrBT5yhJrBwgJgSzTdUKx6HXceuMbM+2We9H5wp1w/62VCmqJqPGE/sEfu4+T2RIVDmmFIjKh0MBKy8mr9jmfwP9BF+65sv0mGo98mkWieh/zC4+nxSZXnJJCskNZjCKZUatE70OheIBm7nXzdRatURKdc3agKp2XY=
services:
- docker
before_script:
- docker login --email='.' --username="${DOCKER_USER}" --password="${DOCKER_PASSWORD}"
  ${DOCKER_REGISTRY}
- wget -O /tmp/dumb-init.tar.gz 'https://github.com/Yelp/dumb-init/archive/v0.5.0.tar.gz'
- tar --strip-components=1 -xf /tmp/dumb-init.tar.gz
- cc -std=gnu99 -static -Wall -Werror -O3 -o dumb-init dumb-init.c
script:
- docker build -t quay.io/docku/dumb-init .
after_script:
- docker push quay.io/docku/dumb-init
